/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clinica.gui;

import clinica.bean.Contato;
import clinica.dao.ContatoDao;
import clinica.util.WebServiceCep;
import clinica.util.guis;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author celso
 */
public class FrmAgenda extends javax.swing.JInternalFrame {

    private DefaultTableModel tabContatos;
    private List<Contato> lista;
    private Contato contatoSel;

    /**
     * Creates new form Agenda
     */
    public FrmAgenda() {
        initComponents();
        PreencheAtividade();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabContatos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        lblTotalContatos = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtPesquisaContato = new clinica.util.JTextUpper();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListFiltroLetra = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        ListAtividade = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtNome = new clinica.util.JTextUpper();
        txtAtiv = new clinica.util.JTextUpper();
        txtEnd = new clinica.util.JTextUpper();
        txtComp = new clinica.util.JTextUpper();
        txtBairro = new clinica.util.JTextUpper();
        txtCidade = new clinica.util.JTextUpper();
        txtEmail = new clinica.util.JTextUpper();
        txtUf = new clinica.util.JTextUpper();
        jLabel16 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtCom1 = new clinica.util.JTextUpper();
        jLabel9 = new javax.swing.JLabel();
        txtCom2 = new clinica.util.JTextUpper();
        jLabel10 = new javax.swing.JLabel();
        txtCel = new clinica.util.JTextUpper();
        jLabel14 = new javax.swing.JLabel();
        txtRes = new clinica.util.JTextUpper();
        jLabel15 = new javax.swing.JLabel();
        txtFax = new clinica.util.JTextUpper();
        txtOp1 = new clinica.util.JTextUpper();
        txtOp2 = new clinica.util.JTextUpper();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtObs = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        btnExcluir = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        txtCep = new javax.swing.JFormattedTextField();
        btnSair = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setTitle("Agenda de Contatos");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Contatos"));

        jTabContatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Comercial 1", "Comercial 2", "Celular"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTabContatos.setToolTipText("Clique para selecionar o contato.");
        jTabContatos.setColumnSelectionAllowed(true);
        jTabContatos.getTableHeader().setReorderingAllowed(false);
        jTabContatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabContatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTabContatos);
        jTabContatos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jTabContatos.getColumnModel().getColumnCount() > 0) {
            jTabContatos.getColumnModel().getColumn(0).setPreferredWidth(300);
            jTabContatos.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTabContatos.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTabContatos.getColumnModel().getColumn(3).setPreferredWidth(100);
        }

        jLabel2.setText("Total de contatos encontrados:");

        lblTotalContatos.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTotalContatos.setForeground(new java.awt.Color(255, 0, 0));
        lblTotalContatos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalContatos.setText("0");

        jLabel18.setText("Pesquisar");

        txtPesquisaContato.setToolTipText("Digite o nome do contato a ser procurado.");
        txtPesquisaContato.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtPesquisaContato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPesquisaContatoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaContatoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTotalContatos, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesquisaContato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtPesquisaContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalContatos)
                    .addComponent(jLabel2))
                .addGap(4, 4, 4))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Opções"));

        ListFiltroLetra.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ListFiltroLetra.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        ListFiltroLetra.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ListFiltroLetra.setToolTipText("Filtra contatos pela letra selecionada.");
        ListFiltroLetra.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ListFiltroLetra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListFiltroLetraMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ListFiltroLetra);

        ListAtividade.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ListAtividade.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ListAtividade.setToolTipText("Filtra contatos pela atividade exercida");
        ListAtividade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListAtividadeMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(ListAtividade);

        jLabel1.setText("Ramo de atividade:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 98, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(7, 7, 7)
                        .addComponent(jScrollPane3))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados"));

        jLabel3.setText("Nome do Contato");

        jLabel4.setText("CEP");

        jLabel5.setText("Endereço");

        jLabel6.setText("Complemento");

        jLabel7.setText("Bairro");

        jLabel11.setText("Cidade");

        jLabel12.setText("E-Mail");

        jLabel13.setText("UF");

        txtNome.setToolTipText("Informe o nome do contato.");
        txtNome.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtAtiv.setToolTipText("Informe a atividade exercida pelo contato.");
        txtAtiv.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtEnd.setToolTipText("Informe o endereço do contato.");
        txtEnd.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtComp.setToolTipText("Informe o número e complemento para o contato.");
        txtComp.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtBairro.setToolTipText("Informe o bairro do contato.");
        txtBairro.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtCidade.setToolTipText("Informe a cidade do contato.");
        txtCidade.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtEmail.setToolTipText("Informe o e-mail do contato.");
        txtEmail.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtUf.setToolTipText("Informe a UF do endereço do contato.");
        txtUf.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel16.setText("Atividade");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Telefones de contato"));

        jLabel8.setText("Comercial 1");

        txtCom1.setToolTipText("Informe o telefone principal do contato.");
        txtCom1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel9.setText("Comercial 2");

        txtCom2.setToolTipText("Informe o telefone secundário do contato.");
        txtCom2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel10.setText("Celular 1");

        txtCel.setToolTipText("Informe o telefone celular do contato.");
        txtCel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel14.setText("Residencial");

        txtRes.setToolTipText("Informe o telefone residêncial do contato.");
        txtRes.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel15.setText("Celular 2");

        txtFax.setToolTipText("Informe o número do fax do contato.");
        txtFax.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtOp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOp2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCom1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txtOp1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtCom2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txtOp2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFax, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtRes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtCom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtCom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(txtOp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        txtObs.setColumns(20);
        txtObs.setLineWrap(true);
        txtObs.setRows(5);
        txtObs.setToolTipText("Informe alguma observações importantes sobre o contato.");
        txtObs.setWrapStyleWord(true);
        jScrollPane4.setViewportView(txtObs);

        jLabel17.setText("Observações");

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinica/imagens/DeleteExame.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setToolTipText("Excluir contato selecionado");
        btnExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinica/imagens/salvar.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setToolTipText("Gravar alterações no contato");
        btnSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinica/imagens/novo.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.setToolTipText("Cadastra um novo contato");
        btnNovo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNovo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        try {
            txtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCep.setToolTipText("Informe o CEP para contato");
        txtCep.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtCep.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCepFocusLost(evt);
            }
        });
        txtCep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCepKeyPressed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinica/imagens/sair.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.setToolTipText("Excluir contato selecionado");
        btnSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtUf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13)))
                            .addComponent(jLabel7))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btnNovo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnSalvar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnExcluir)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSair))
                            .addComponent(jScrollPane4)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(txtAtiv, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtEnd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtComp, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(12, 12, 12))))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnExcluir, btnNovo, btnSair, btnSalvar});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel16)
                    .addComponent(jLabel12))
                .addGap(2, 2, 2)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAtiv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)))
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnExcluir)
                                .addComponent(btnSalvar)
                                .addComponent(btnNovo))
                            .addComponent(btnSair, javax.swing.GroupLayout.Alignment.TRAILING)))))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnExcluir, btnNovo, btnSair, btnSalvar});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListFiltroLetraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListFiltroLetraMouseClicked
        String letra = (String) ListFiltroLetra.getSelectedValue();

        ContatoDao contato = new ContatoDao();
        this.lista = contato.ListaContatoLetra(letra.trim());

        PreencheTabela(this.lista);
    }//GEN-LAST:event_ListFiltroLetraMouseClicked

    private void ListAtividadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListAtividadeMouseClicked
        ContatoDao contato = new ContatoDao();
        this.lista = contato.ListaContatoAtividade(ListAtividade.getSelectedValue().toString());

        PreencheTabela(this.lista);
    }//GEN-LAST:event_ListAtividadeMouseClicked

    private void jTabContatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabContatosMouseClicked
        if (jTabContatos.getSelectedRow() >= 0) {
            PreencheCampos(this.lista.get(jTabContatos.getSelectedRow()));
            System.out.println("ID Selecionado: " + this.lista.get(jTabContatos.getSelectedRow()).getAgID());
        }
    }//GEN-LAST:event_jTabContatosMouseClicked

    private void txtPesquisaContatoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaContatoKeyPressed
    }//GEN-LAST:event_txtPesquisaContatoKeyPressed

    private void txtPesquisaContatoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaContatoKeyReleased
        ContatoDao contato = new ContatoDao();

        if (!(evt.getKeyCode() == KeyEvent.VK_BACK_SPACE)) {
            if (!txtPesquisaContato.getText().equals("")) {
                this.lista = contato.BuscarContato(txtPesquisaContato.getText());

                if (this.lista.isEmpty()) {
                    PreencheTabela(this.lista);
                    JOptionPane.showMessageDialog(this, "Nenhum contato encontrado!");
                } else {
                    PreencheTabela(this.lista);
                }
            }
        }
    }//GEN-LAST:event_txtPesquisaContatoKeyReleased

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        LimparCampos();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        if (!txtNome.getText().equals("")) {
            ContatoDao contatoDao = new ContatoDao();

            if (contatoSel == null) {
                // Inserindo novo contato
                Contato c1 = new Contato();

                c1.setAgNome(txtNome.getText());
                c1.setAgAtividade(txtAtiv.getText());
                c1.setAgEmail(txtEmail.getText());
                if (!txtCep.getText().equals("     -   ")) {
                    String cep = txtCep.getText();
                    String cepReplace = cep.replace("-", "");
                    c1.setAgCep(Integer.parseInt(cepReplace));
                }

                //c1.setAgCep(Integer.parseInt(txtCep.getText()));
                
                c1.setAgEnd(txtEnd.getText());
                c1.setAgComp(txtComp.getText());
                c1.setAgBairro(txtBairro.getText());
                c1.setAgCidade(txtCidade.getText());
                c1.setAgUf(txtUf.getText());
                c1.setAgTelCom1(txtCom1.getText());
                c1.setAgTelCom2(txtCom2.getText());
                c1.setAgTelCel(txtCel.getText());
                c1.setAgTelRes(txtRes.getText());
                c1.setAgTelFax(txtFax.getText());
                c1.setAgObs(txtObs.getText());

                if (contatoDao.AdicionaContato(c1) != 1) {
                    JOptionPane.showMessageDialog(this, "Erro ao adicionar novo contato!", "Novo contato", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                // Aterando contato selecionado
                Contato c1 = new Contato();

                c1.setAgID(contatoSel.getAgID());
                c1.setAgNome(txtNome.getText());
                c1.setAgAtividade(txtAtiv.getText());
                c1.setAgEmail(txtEmail.getText());
                if (!txtCep.getText().equals("     -   ")) {
                    String cep = txtCep.getText();
                    String cepReplace = cep.replace("-", "");
                    c1.setAgCep(Integer.parseInt(cepReplace));
                }

                // c1.setAgCep(Integer.parseInt(txtCep.getText()));
                
                c1.setAgEnd(txtEnd.getText());
                c1.setAgComp(txtComp.getText());
                c1.setAgBairro(txtBairro.getText());
                c1.setAgCidade(txtCidade.getText());
                c1.setAgUf(txtUf.getText());
                c1.setAgTelCom1(txtCom1.getText());
                c1.setAgTelCom2(txtCom2.getText());
                c1.setAgTelCel(txtCel.getText());
                c1.setAgTelRes(txtRes.getText());
                c1.setAgTelFax(txtFax.getText());
                c1.setAgObs(txtObs.getText());

                if (contatoDao.AtualizaContato(c1) != 1) {
                    JOptionPane.showMessageDialog(this, "Erro ao adicionar novo contato!", "Novo contato", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Você precisa informar o nome para o contato!", "Novo contato", JOptionPane.ERROR_MESSAGE);
        }
        PreencheAtividade();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (this.contatoSel != null) {
            if (JOptionPane.showConfirmDialog(this, "Deseja realmente excluir contato selecionado?", "ATENÇÃO", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
                
                ContatoDao contato = new ContatoDao();
                
                if (contato.ExcluirContato(this.contatoSel.getAgID()) != 1) {
                    JOptionPane.showMessageDialog(this, "Erro ao excluir contato!", "ATENÇÃO", JOptionPane.ERROR_MESSAGE);
                } else {
                    LimparCampos();
                    ListAtividadeMouseClicked(null);
                    //jTabContatos.remove(jTabContatos.getSelectedRow());
                    //tabContatos.removeRow(jTabContatos.getSelectedRow());
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Você precisa selecionar um contato para exclusão!", "ATENÇÃO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void txtCepFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCepFocusLost
        System.out.println("Key released... buscando endereco pelo CEP:");

        if (!txtCep.getText().equals("     -   ")) {
            WebServiceCep buscaCep = WebServiceCep.searchCep(txtCep.getText());

            if (buscaCep.wasSuccessful()) {
                txtEnd.setText(buscaCep.getLogradouroFull());
                txtBairro.setText(buscaCep.getBairro());
                txtCidade.setText(buscaCep.getCidade());
                txtUf.setText(buscaCep.getUf());
                txtComp.requestFocus();
            } else {
                txtEnd.requestFocus();
            }
        }
    }//GEN-LAST:event_txtCepFocusLost

    private void txtCepKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCepKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!(txtCep.getText().isEmpty()) || (txtCep.getText().length() != 9)) {
                txtCepFocusLost(null);
            }
        }
    }//GEN-LAST:event_txtCepKeyPressed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        guis.setiAgenda(null);
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void txtOp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOp2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOp2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList ListAtividade;
    private javax.swing.JList ListFiltroLetra;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTabContatos;
    private javax.swing.JLabel lblTotalContatos;
    private clinica.util.JTextUpper txtAtiv;
    private clinica.util.JTextUpper txtBairro;
    private clinica.util.JTextUpper txtCel;
    private javax.swing.JFormattedTextField txtCep;
    private clinica.util.JTextUpper txtCidade;
    private clinica.util.JTextUpper txtCom1;
    private clinica.util.JTextUpper txtCom2;
    private clinica.util.JTextUpper txtComp;
    private clinica.util.JTextUpper txtEmail;
    private clinica.util.JTextUpper txtEnd;
    private clinica.util.JTextUpper txtFax;
    private clinica.util.JTextUpper txtNome;
    private javax.swing.JTextArea txtObs;
    private clinica.util.JTextUpper txtOp1;
    private clinica.util.JTextUpper txtOp2;
    private clinica.util.JTextUpper txtPesquisaContato;
    private clinica.util.JTextUpper txtRes;
    private clinica.util.JTextUpper txtUf;
    // End of variables declaration//GEN-END:variables

    private void PreencheTabela(List<Contato> lista) {
        DefaultTableModel tabContatos = (DefaultTableModel) jTabContatos.getModel();

        tabContatos.setRowCount(0);

        if (!this.lista.isEmpty()) {
            for (int i = 0; i < lista.size(); i++) {
                tabContatos.addRow(new String[]{null, null, null, null});
                tabContatos.setValueAt(lista.get(i).getAgNome(), i, 0);
                tabContatos.setValueAt(lista.get(i).getAgTelCom1(), i, 1);
                tabContatos.setValueAt(lista.get(i).getAgTelCom2(), i, 2);
                tabContatos.setValueAt(lista.get(i).getAgTelCel(), i, 3);
            }
        }
        lblTotalContatos.setText(String.valueOf(jTabContatos.getRowCount()));
    }

    private void PreencheCampos(Contato contato) {
        txtNome.setText(contato.getAgNome());
        txtAtiv.setText(contato.getAgAtividade());
        txtEmail.setText(contato.getAgEmail());
        // Endereco
        txtCep.setText(String.valueOf(contato.getAgCep()));
        txtEnd.setText(contato.getAgEnd());
        txtComp.setText(contato.getAgComp());
        txtBairro.setText(contato.getAgBairro());
        txtCidade.setText(contato.getAgCidade());
        txtUf.setText(contato.getAgUf());
        // Telefones
        txtCom1.setText(contato.getAgTelCom1());
        txtCom2.setText(contato.getAgTelCom2());
        txtCel.setText(contato.getAgTelCel());
        txtRes.setText(contato.getAgTelRes());
        txtFax.setText(contato.getAgTelFax());
        // observacoes
        txtObs.setText(contato.getAgObs());

        this.contatoSel = contato;
    }

    private void PreencheAtividade() {
        ContatoDao contato = new ContatoDao();
        List atividade = contato.listaAtividades();

        DefaultListModel model = new DefaultListModel();
        JList list = new JList(model);

        for (int i = 0; i < atividade.size(); i++) {
            model.add(i, atividade.get(i));
        }

        ListAtividade.setModel(model);
    }

    private void LimparCampos() {
        txtNome.setText("");
        txtAtiv.setText("");
        txtEmail.setText("");
        // Endereco
        txtCep.setText("");
        txtEnd.setText("");
        txtComp.setText("");
        txtBairro.setText("");
        txtCidade.setText("");
        txtUf.setText("");
        // Telefones
        txtCom1.setText("");
        txtCom2.setText("");
        txtCel.setText("");
        txtRes.setText("");
        txtFax.setText("");
        // observacoes
        txtObs.setText("");

        this.contatoSel = null;

        txtNome.requestFocus();
    }
}
