/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clinica.gui;

import clinica.bean.Exame;
import clinica.bean.TabelaPrecos;
import clinica.dao.ExameDao;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author celso
 */
public class FrmAddExame extends javax.swing.JFrame {

    private String tabNome;
    private List<TabelaPrecos> tabList;

    /**
     * Creates new form AddExame
     */
    public FrmAddExame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblCol1 = new javax.swing.JLabel();
        lblCol2 = new javax.swing.JLabel();
        txtNomeExame = new clinica.util.JTextUpper();
        jLabel4 = new javax.swing.JLabel();
        cmbTabela = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        txtLab1 = new javax.swing.JFormattedTextField();
        txtLab2 = new javax.swing.JFormattedTextField();
        txtFinal = new javax.swing.JFormattedTextField();
        btnSalvarExame = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adicionar novo exame");
        setAlwaysOnTop(true);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do novo exame"));

        jLabel1.setText("Nome:");

        lblCol1.setText("Preço Lab1:");

        lblCol2.setText("Preço Lab2:");

        txtNomeExame.setToolTipText("Digite o nome para o novo exame");
        txtNomeExame.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtNomeExame.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomeExameFocusLost(evt);
            }
        });

        jLabel4.setText("Preço Final:");

        jLabel5.setText("Tabela:");

        txtLab1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));
        txtLab1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtLab1.setToolTipText("");
        txtLab1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtLab2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        txtLab2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtLab2.setToolTipText("");
        txtLab2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtFinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        txtFinal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtFinal.setToolTipText("");
        txtFinal.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblCol1)
                                .addGap(18, 18, 18)
                                .addComponent(txtLab1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblCol2)
                                    .addComponent(jLabel4))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(txtLab2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txtFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeExame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtFinal, txtLab1, txtLab2});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNomeExame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbTabela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCol1)
                            .addComponent(txtLab1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLab2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCol2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(17, 17, 17))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtFinal, txtLab1, txtLab2});

        btnSalvarExame.setText("Cadastrar");
        btnSalvarExame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarExameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalvarExame)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalvarExame)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeExameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeExameFocusLost
        if (!(txtNomeExame.getText().equals("") || txtNomeExame.getText().isEmpty())) {
            ExameDao exDao = new ExameDao();
            if (exDao.VerifcaExameExiste(txtNomeExame.getText().trim())) {
                JOptionPane.showMessageDialog(this, "Exame já existe na base de dados");
            }
        }
    }//GEN-LAST:event_txtNomeExameFocusLost

    private void btnSalvarExameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarExameActionPerformed
        if (!(txtNomeExame.getText().isEmpty() || txtNomeExame.getText().equals(""))) {

            String col1 = txtLab1.getText().replace(",", ".");
            String col2 = txtLab2.getText().replace(",", ".");
            String precofinal = txtFinal.getText().replace(",", ".");
            
            Exame exame = new Exame();
            
            exame.setExNome(txtNomeExame.getText());
            exame.setExCol1(Double.parseDouble(col1));
            exame.setExCol2(Double.parseDouble(col2));
            exame.setExPreco(Double.parseDouble(precofinal));
            exame.setExTab( tabList.get(cmbTabela.getSelectedIndex()).getTexID() );
            
            ExameDao exDao = new ExameDao();

            if (exDao.AdicionaExame(exame) == 0) {
                JOptionPane.showMessageDialog(this, "Erro ao adicionar exame! ", "Erro!", JOptionPane.ERROR_MESSAGE);
            } else {
                this.dispose();
            }
        }
    }//GEN-LAST:event_btnSalvarExameActionPerformed

    public void PreencherCombo(List<TabelaPrecos> tabela) {
        //TabelaPrecosDao TabPrecos = new TabelaPrecosDao();

        //List<TabelaPrecos> tab = TabPrecos.BuscaTabela();
        for (TabelaPrecos tab1 : tabela) {
            cmbTabela.addItem(tab1.getTexNome());
        }
        
        System.out.println(this.tabNome);
        if(!this.tabNome.equals("")){
           cmbTabela.setSelectedItem(this.tabNome);
        }
    }

    public void setTabela(String Nome, List<TabelaPrecos> tabList) {
        this.tabNome = Nome;
        this.tabList = tabList;
    }

    public void setCols(String col1, String col2){
        lblCol1.setText(col1);
        lblCol2.setText(col2);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvarExame;
    private javax.swing.JComboBox cmbTabela;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCol1;
    private javax.swing.JLabel lblCol2;
    private javax.swing.JFormattedTextField txtFinal;
    private javax.swing.JFormattedTextField txtLab1;
    private javax.swing.JFormattedTextField txtLab2;
    private clinica.util.JTextUpper txtNomeExame;
    // End of variables declaration//GEN-END:variables
}
