/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmLogin.java
 *
 * Created on 06/11/2011, 12:38:40
 */
package clinica.gui;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import clinica.dao.UsuarioDao;
import clinica.util.Md5;

/**
 *
 * @author celso
 */
public class FrmLogin extends javax.swing.JFrame {

    /**
     * Creates new form FrmLogin
     */
    //Connection mycon = ConexaoSQlite.getConexao();

    public FrmLogin() {
        initComponents();
        //lbl_cadeado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sigma/imagens/security.png")))
        this.setIconImage(new ImageIcon(getClass().getResource("/clinica/imagens/cadeado.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_cadeado = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfLogin = new javax.swing.JTextField();
        btnOK = new javax.swing.JButton();
        lbl_erros = new javax.swing.JLabel();
        tfPass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Policlínica login");
        setResizable(false);

        lbl_cadeado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinica/imagens/security.png"))); // NOI18N

        jLabel2.setText("Login:");

        jLabel3.setText("Senha:");

        tfLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfLoginKeyPressed(evt);
            }
        });

        btnOK.setText("OK");
        btnOK.setSelected(true);
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        lbl_erros.setForeground(new java.awt.Color(255, 0, 0));
        lbl_erros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        tfPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfPassKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_erros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_cadeado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfPass)
                            .addComponent(tfLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(7, 7, 7)
                        .addComponent(tfPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnOK))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_cadeado, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                        .addGap(33, 33, 33)))
                .addComponent(lbl_erros, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reset() {
        tfLogin.setText(null);
        tfPass.setText(null);
        tfLogin.requestFocus();
    }

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed

        Md5 t = new Md5();
        String login = tfLogin.getText();
        String senha = tfPass.getText();
        
        System.out.println(t.crypt(senha));

        lbl_erros.setText(null);
        if (tfLogin.getText().isEmpty() || tfPass.getText().isEmpty()) {
            lbl_erros.setForeground(Color.red);
            lbl_erros.setText("Preencha corretamente os campos acima!");
            this.reset();
        } else {
            UsuarioDao user = new UsuarioDao();
            
            if( user.ValidaLogin(login, senha) ){
                FrmPrincipal fp = new FrmPrincipal();
                fp.setLocationRelativeTo(null);
                //fp.setExtendedState(MAXIMIZED_BOTH);
                fp.setVisible(true);
                this.dispose();
            } else {
                System.out.println("Nao encontrei voce");
                lbl_erros.setText("Usuário ou senha incorreta!");
            }
        }
    }//GEN-LAST:event_btnOKActionPerformed

    private void tfLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfLoginKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            tfPass.requestFocus();
        }
    }//GEN-LAST:event_tfLoginKeyPressed

    private void tfPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPassKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnOKActionPerformed(null);
        }
    }//GEN-LAST:event_tfPassKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbl_cadeado;
    private javax.swing.JLabel lbl_erros;
    private javax.swing.JTextField tfLogin;
    private javax.swing.JPasswordField tfPass;
    // End of variables declaration//GEN-END:variables
}
