/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clinica.gui;

import clinica.bean.TabelaPrecos;
import clinica.dao.TabelaPrecosDao;
import javax.swing.JOptionPane;

/**
 *
 * @author celso
 */
public class FrmNewTabelaExame extends javax.swing.JFrame {

    FrmPrecos fPrecos;
    TabelaPrecos tab;

    /**
     * Creates new form FrmNewTabelaExame
     */
    public FrmNewTabelaExame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSaveTab = new javax.swing.JButton();
        txtNomeTab = new clinica.util.JTextUpper();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCol1 = new javax.swing.JTextField();
        txtCol2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tabela de Exame/procedimentos");

        btnSaveTab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinica/imagens/salvar.png"))); // NOI18N
        btnSaveTab.setText("Salvar");
        btnSaveTab.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSaveTab.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSaveTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveTabActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome:");

        jLabel2.setText("COL 1:");

        jLabel3.setText("COL 2:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCol1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCol2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSaveTab)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNomeTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSaveTab)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCol1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCol2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveTabActionPerformed
        if (txtNomeTab.getText().isEmpty() || txtNomeTab.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Você precisa preencher o nome do exame/procedimento.", "Alerta", JOptionPane.ERROR_MESSAGE);
        } else {
            TabelaPrecosDao tabDao = new TabelaPrecosDao();

            if (this.tab != null) {
                this.tab.setTexNome(txtNomeTab.getText());
                this.tab.setTexCol1(txtCol1.getText());
                this.tab.setTexCol2(txtCol2.getText());

                if (tabDao.EditarTabela(this.tab) == 1) {
                    JOptionPane.showMessageDialog(this, "Tabela alterada com sucesso!");
                    fPrecos.BuscaTabelas();
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao tentar editar tabela!", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                TabelaPrecos tabelaPrecos = new TabelaPrecos();

                tabelaPrecos.setTexNome(txtNomeTab.getText());
                tabelaPrecos.setTexCol1(txtCol1.getText());
                tabelaPrecos.setTexCol2(txtCol2.getText());

                if (tabDao.AdicionaTabela(tabelaPrecos) == 1) {
                    JOptionPane.showMessageDialog(this, "Tabela criada com sucesso!");
                    fPrecos.BuscaTabelas();
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao tentar criar nova tabela!", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        
        this.dispose();
    }//GEN-LAST:event_btnSaveTabActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveTab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtCol1;
    private javax.swing.JTextField txtCol2;
    private clinica.util.JTextUpper txtNomeTab;
    // End of variables declaration//GEN-END:variables

    public void RecebeTabela(FrmPrecos fprecos, TabelaPrecos tab) {
        txtNomeTab.setText(tab.getTexNome());
        txtCol1.setText(tab.getTexCol1());
        txtCol2.setText(tab.getTexCol2());

        this.fPrecos = fprecos;
        this.tab = tab;
    }

    void RecebeTabelaNova(FrmPrecos aThis) {
        this.fPrecos = aThis;
    }
}
